# Generated by Django 6.0.7 on 2026-07-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], default='baja', max_length=10)),
                ('fecha_creada', models.DateField(auto_now_add=True)),
                ('fecha_actualizada', models.DateField(auto_now=True)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
